handcricketReset/urls.py
from operator import index
from player import views
from django.contrib import admin
from django.urls import path
# from numpy import r_
from django.conf.urls import include
from django.urls import include,path
from player import urls
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
router = routers.DefaultRouter()
router.register('iplteams',views.IPLTeamView, basename='iplteams')
router.register('players',views.PlayerView, basename='players')
router.register('intlteams',views.INTLTeamView, basename='intlteams')
router.register('users',views.UserView, basename='users')
router.register('profileextends',views.ProfileExtendView, basename='profileextends')
# router.register('users',views.User, basename='users')
# router.register('profileextends',views.ProfileExtendView, basename='profileextends')
# routeriplteams = routers.DefaultRouter()
# routeriplteams.register('iplteams',views.IPLTeamView, basename='iplteams')
# routerintlteams = routers.DefaultRouter()
# routerintlteams.register('intlteams',views.INTLTeamView, basename='intlteams')
# routerusers = routers.DefaultRouter()
# routerusers.register('users',views.UserView, basename='users')
# routerprofileextend = routers.DefaultRouter()
# routerprofileextend.register('profileextends',views.UserView, basename='profileextends')
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('player.urls',namespace='player')),
    path('login/',auth_views.LoginView.as_view(template_name="registration/login.html"),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('signup/',views.SignUp.as_view(),name='signup'),
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path('api/',include(router.urls)),
]
if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

player/urls.py
from operator import index
from django.shortcuts import render
from player import views
from django.contrib import admin
from django.urls import path
# from numpy import place, r_
from django.conf.urls import include
from django.contrib.auth import views as auth_views
from player import views
app_name = 'player'

urlpatterns = [
    path('',views.AboutView,name='about'),
    path('IPLTeamList/',views.IPLTeamListView.as_view(),name='IPLTeamList'),
    path('newiplteam/',views.CreateIPLTeam.as_view(),name='newiplteam'),
    path('IPLTeamDetail/<int:pk>/',views.IPLTeamDetailView.as_view(),name='IPLTeamDetail'),
    path('IPLTeamUpdate/<int:pk>/',views.IPLTeamUpdateView.as_view(),name='IPLTeamUpdate'),
    path('IPLTeamDelete/<int:pk>/',views.IPLTeamDeleteView.as_view(),name='IPLTeamDelete'),
    path('newintlteam/',views.CreateINTLTeam.as_view(),name='newintlteam'),
    path('INTLTeamList/',views.INTLTeamListView.as_view(),name='INTLTeamList'),
    path('INTLTeamDetail/<int:pk>',views.INTLTeamDetailView.as_view(),name='INTLTeamDetail'),
    path('INTLTeamUpdate/<int:pk>/',views.INTLTeamUpdateView.as_view(),name='INTLTeamUpdate'),
    path('INTLTeamDelete/<int:pk>/',views.INTLTeamDeleteView.as_view(),name='INTLTeamDelete'),
    path('newplayer/',views.CreatePLayer.as_view(),name='newplayer'),
    path('PlayerList/',views.PlayerList.as_view(),name='PlayerList'),
    path('PlayerDetail/<int:pk>/',views.PlayerDetailView.as_view(),name='PlayerDetail'),
    path('PlayerUpdate/<int:pk>/',views.PLayerUpdateView.as_view(),name='PlayerUpdate'),
    path('PlayerDelete/<int:pk>/',views.PLayerDeleteView.as_view(),name='PlayerDelete'),
    path('MyProfile/',views.my_profile,name='MyProfile'),
    path('Playersofintlteam/<int:pk>',views.get_players_of_intl_team,name='Playersofintlteam'),
    path('Playersofipllteam/<int:pk>',views.get_players_of_ipl_team,name='Playersofiplteam'),
    path('ODITeamX1/<int:pk>/',views.ODITeamX1,name='ODITeamX1'),
    path('TestTeamX1/<int:pk>/',views.TestTeamX1,name='TestTeamX1'),
    path('T20TeamX1/<int:pk>/',views.T20TeamX1,name='T20TeamX1'),
    path('IPLTeamX1/<int:pk>/',views.IPLTeamX1,name='IPLTeamX1'),
    path('GiftPlayer/<int:pk>/',views.gift_player,name="GiftPlayer"),
    path('MyT20TeamX1/',views.MyT20TeamX1,name='MyT20TeamX1'),
    path('MYIPLTeamX1/',views.MYIPLTeamX1,name='MYIPLTeamX1'),
    path('MyTestTeamX1/',views.MyTestTeamX1,name='MyTestTeamX1'),
    path('MyODITeamX1/',views.MyODITeamX1,name='MyODITeamX1'),
    path('worldODIXI/',views.worldODIXI,name='worldODIXI'),
    path('worldTestXI/',views.worldTestXI,name='worldTestXI'),
    path('worldT20XI/',views.worldT20XI,name='worldT20XI'),
    path('IPLXI/',views.IPLXI,name='IPLXI'),
    path('ExtraProfile/',views.ExtraProfile.as_view(),name='ExtraProfile'),
    path('ProfileUpdateView/',views.ProfileUpdateView.as_view(),name='ProfileUpdateView'),
    path('ViewStats/',views.ViewStats,name='ViewStats'),
    path('ViewMyStats/',views.viewuserStats,name='ViewMyStats'),
    path('search_venues/',views.search_venues,name='search_venues'),
]

player/forms.py
from dataclasses import fields
import imp
from pyexpat import model
from unittest.util import _MAX_LENGTH
from wsgiref.validate import validator
import django
from django.core import validators
from django import forms
from player.models import INTLTeam,IPLTeam,Player,User,Profile_extend
from django.contrib.auth.models import User
from . models import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UserCreateForm(UserCreationForm):
    # first_name = forms.CharField(max_length=50)
    # last_name = forms.CharField(max_length=50)
    # Twitter = forms.URLField(max_length=300,required=False)
    # Facebook = forms.URLField(max_length=300,required=False)
    # Instagram = forms.URLField(max_length=300,required=False)
    # LinkedIn = forms.URLField(max_length=300,required=False)
    # Github = forms.URLField(max_length=300,required=False)
    # bio = forms.CharField(max_length=150)
    class Meta:
        fields = ("first_name","last_name","username", "email", "password1", "password2")
        # fields = ("__all__")
        model = get_user_model()
class UserUpdateForm(UserCreationForm):
    class Meta:
        fields = ("first_name","last_name", "email")
        # fields = ("__all__")
        model = get_user_model()

class EditUserForm(forms.ModelForm):
    class Meta:
        model = Profile_extend
        fields = ("Twitter","Facebook","Instagram","LinkedIn","Github","bio","birth_date","location")
        # fields = ("Twitter","Facebook","Instagram","LinkedIn","Github","bio","birth_date","location","user_img")
        # widgets = {
        #     'ownerplayer': forms.Select(attrs={'class': 'form-control'}),
        # }

class GiftPlayer(forms.ModelForm):
    class Meta:
        model = Player
        fields = ('ownerplayer',)
        # widgets = {
        #     'ownerplayer': forms.Select(attrs={'class': 'form-control'}),
        # }

class PlayerCreationForm:
    class Meta:
        model = Player
        fields = ('ownerplayer',)
        widgets = {
            'ownerplayer' : forms.Select(attrs={'class':'form-control','label':'Owner'}),
        }

player/views.py
from django import http
from django.shortcuts import render,get_object_or_404,redirect
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse_lazy
from django.urls import reverse
from django.utils import timezone
# from matplotlib.style import context  # changed for env311
# from numpy import sort  # changed for env311
from player import models
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User, auth
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.db.models import Q
# FOR MTV
from player.models import INTLTeam,IPLTeam,Player,User,Profile_extend
# from player.forms import UserCreateForm,GiftPlayer,EditUserForm,UserUpdateForm,PlayerCreationForm
from player.forms import UserCreateForm,GiftPlayer,UserUpdateForm,PlayerCreationForm,EditUserForm
# FOR CBV
from django.views.generic import View,TemplateView,ListView,DetailView,CreateView,UpdateView,DeleteView
# for REST API
from rest_framework import viewsets
from rest_framework import generics
from rest_framework.generics import ListAPIView
from .serializer import PlayerSerializer,INTLTeamSerializer,IPLTeamSerializer, UserSerializer, ProfileExtendSerializer

usernameglobal = get_user_model()
# Create your views here.

# REST API
class PlayerView(viewsets.ModelViewSet):
    serializer_class = PlayerSerializer
    queryset = Player.objects.all()
class INTLTeamView(viewsets.ModelViewSet):
    serializer_class = INTLTeamSerializer
    queryset = INTLTeam.objects.all()
class IPLTeamView(viewsets.ModelViewSet):
    serializer_class = IPLTeamSerializer
    queryset = IPLTeam.objects.all()
class UserView(viewsets.ModelViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
class ProfileExtendView(viewsets.ModelViewSet):
    serializer_class = ProfileExtendSerializer
    queryset = Profile_extend.objects.all()
# class UserView(viewsets.ModelViewSet):
#     serializer_class 

# REST API ENDED

def search_venues(request):
    if request.method == "POST":
        searched = request.POST['searched']
        players = Player.objects.filter(name__contains=searched)
        return render(request, 'registration/search_venues.html',{'searched':searched,'players':players})
    else:
        return render(request, 'registration/search_venues.html',{})


class ExtraProfile(CreateView):
    model = Profile_extend
    # Profile.objects.create(user=request.user)
    # fields = ['Twitter','Facebook','Instagram','LinkedIn','Github','bio','birth_date','location']
    fields = '__all__'

# class AboutView(TemplateView):
#     template_name = 'registration/about.html'
def AboutView(request):
    return render(request,'registration/about.html')

class TestPage(TemplateView):
    template_name = 'registration/test.html'

class ThanksPage(TemplateView):
    template_name = 'registration/thanks.html'

class SignUp(CreateView):
    form_class = UserCreateForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

class CreateIPLTeam(CreateView):# this needs a default template "modelname_form"
    model = IPLTeam
    fields = '__all__'
    # form_class = IPLTeamForm
    

class IPLTeamListView(ListView):# this needs a default template "modelname_list"
    model = IPLTeam
    context_object_name = 'IPLTeam_list'
    no_of_teams = IPLTeam.objects.count()
    extra_context = {'no_of_teams' : no_of_teams}
    
    def get_queryset(self):
        return IPLTeam.objects.order_by('trophies_won')

class IPLTeamDetailView(DetailView,LoginRequiredMixin):# this needs a default template "modelname_detail"
    model = IPLTeam
    context_object_name = 'iplteam'



class IPLTeamUpdateView(UpdateView,LoginRequiredMixin):
    model = IPLTeam
    fields = ['matches_played','matches_won','matches_lost','trophies_won']
    success_url = "/"
class IPLTeamDeleteView(DeleteView,LoginRequiredMixin):
    model = IPLTeam
    success_url = reverse_lazy('player:IPLTeamList')

class CreateINTLTeam(CreateView,LoginRequiredMixin):# this needs a default template "modelname_form"
    model = INTLTeam
    fields = '__all__'
    # template_name='player/intlteam_form.html'

class INTLTeamListView(ListView,LoginRequiredMixin):# this needs a default template "modelname_list"
    model = INTLTeam
    context_object_name = 'INTLTeam_list'
    no_of_teams = INTLTeam.objects.count()
    extra_context = {'no_of_teams' : no_of_teams}
    
    # def get_queryset(self):
    #     return INTLTeam.objects.order_by('trophies_won')
class INTLTeamDetailView(DetailView,LoginRequiredMixin):# this needs a default template "modelname_detail"
    model = INTLTeam
    context_object_name = 'intlteam'

# def INTLTeamDetailView(request,id):
#     model = IPLTeam
#     context = {}
#     context['data'] = IPLTeam.objects.get(id = id)
#     return render(request,'player/intlteam_detail.html')

class INTLTeamUpdateView(UpdateView,LoginRequiredMixin):
    model = INTLTeam
    # fields = ['World_cups_won','Champion_trophies_won','T20WC_trophies_won','Asia_Cups_Won','ODI_matches_played','Test_matches_played','T20_matches_played','flagintl']
    fields = ['World_cups_won','Champion_trophies_won','T20WC_trophies_won','Asia_Cups_Won','ODI_matches_played','Test_matches_played','T20_matches_played']
    success_url = "/"

class INTLTeamDeleteView(DeleteView,LoginRequiredMixin):
    model = INTLTeam
    success_url = reverse_lazy('player:IPLTeamList')

class CreatePLayer(CreateView,LoginRequiredMixin):# this needs a default template "modelname_form"
    model = Player
    form = PlayerCreationForm
    fields = '__all__'
    # fields = ['name','player_image',
    # 'iplteam','intlteam','age','jersey_number',
    # 'Role','batting_position','ODIs_played',
    # 'ODIs_innings_played','highest_scoreODI',
    # 'total_runsODI','total_balls_facedODI',
    # 'not_outsODI','fiftiesODI','hundredsODI',
    # 'innings_bowled_ODI','total_bowlsODI',
    # 'total_runs_givenODI','wicketsODI','IPLs_played',
    # 'IPLs_innings_played','highest_scoreIPL',
    # 'total_runsIPL','total_balls_facedIPL',
    # 'not_outsIPL','fiftiesIPL','hundredsIPL',
    # 'innings_bowled_IPL','total_bowlsIPL',
    # 'total_runs_givenIPL','wicketsIPL','Tests_played',
    # 'Tests_innings_played','highest_scoreTest',
    # 'total_runsTest','total_balls_facedTest',
    # 'not_outsTest','fiftiesTest','hundredsTest',
    # 'innings_bowled_Test','total_bowlsTest',
    # 'total_runs_givenTest','wicketsTest',
    # 'T20s_played','T20s_innings_played',
    # 'highest_scoreT20','total_runsT20',
    # 'total_balls_facedT20','not_outsT20','fiftiesT20',
    # 'hundredsT20','innings_bowled_T20','total_bowlsT20',
    # 'total_runs_givenT20','wicketsT20']
        
class PlayerDetailView(DetailView,LoginRequiredMixin):# this needs a default template "modelname_detail"
    model = Player
    context_object_name = 'player'

class PlayerList(ListView,LoginRequiredMixin):
    model = Player
    context_object_name = 'player_list'
    Batsman = "Batsman"
    Batting_Allrounder = "Batting Allrounder"
    Bowling_Allrounder = "Bowling Allrounder"
    Fast_Bowler = "Fast Bowler"
    Spin_Bowler = "Spin Bowler"
    no_of_players = Player.objects.all().count()
    # batsman = Player.objects.all().filter('player__Role__exact=Batsman')
    # batting_Allrounder = Player.objects.all().filter('player__Role__exact=Batting_Allrounder')
    # bowling_Allrounder = Player.objects.all().filter('player__Role__exact=Bowling_Allrounder')
    # fast_Bowler = Player.objects.all().filter('player__Role__exact=Fast_Bowler')
    # spin_Bowler = Player.objects.all().filter('player__Role__exact=Spin_Bowler')
  
    extra_context = {
        'no_of_players' : no_of_players,
        # 'batsman' : batsman,
        # 'battingAllrounder' : batting_Allrounder,
        # 'bowlingAllrounder' : bowling_Allrounder,
        # 'fastBowler' : fast_Bowler,
        # 'spinBowler' : spin_Bowler,
    }

class PLayerUpdateView(UpdateView,LoginRequiredMixin):
    model = Player
    fields = '__all__'
    success_url = "/"

class PLayerDeleteView(DeleteView,LoginRequiredMixin):
    model = Player
    success_url = reverse_lazy('player:about')





    # iplteam = models.ForeignKey(IPLTeam,on_delete=models.CASCADE)
    # intlteam = models.ForeignKey(INTLTeam,on_delete=models.CASCADE)
    # name = models.CharField(max_length=20)
    # age = models.IntegerField()
    # highest_score = models.IntegerField()
    # total_runs = models.IntegerField()
    # not_outs = models.IntegerField()
    # bat_avg = models.IntegerField()
    # total_bowls = models.IntegerField()
    # wickets = models.IntegerField()
    # bowl_avg = models.IntegerField()
    # jersey_number = models.IntegerField(default=0)   

# def signup(request):

#     if request.method == 'POST':
#         username = request.POST['username']
#         email = request.POST['email']
#         password = request.POST['password']
#         password2 = request.POST['password2']

#         if password == password2:
#             if User.objects.filter(email=email).exists():
#                 messages.info(request, 'Email Taken')
#                 return redirect('signup')
#             elif User.objects.filter(username=username).exists():
#                 messages.info(request, 'Username Taken')
#                 return redirect('signup')
#             else:
#                 user = User.objects.create_user(username=username, email=email, password=password)
#                 user.save()

#                 #log user in and redirect to settings page
#                 user_login = auth.authenticate(username=username, password=password)
#                 auth.login(request, user_login)


#                 return redirect('player:PlayerList')
#         else:

templates/player/intlteam_detail.html
{%extends 'registration/base.html'%}

{% block content %}
hello, this is the intlteam_detail page
{{hi}}
<h1>The name of the team is : {{intlteam.name}}</h1>
<h1>The total number of ODI matches played by {{intlteam.name}} are : {{intlteam.ODI_matches_played}}</h1>
<h1>The total number of Test matches played by {{intlteam.name}} are : {{intlteam.Test_matches_played}}</h1>
<h1>The total number of T20 matches played by {{intlteam.name}} are : {{intlteam.T20_matches_played}}</h1>
<h1>The total number World Cups won by {{intlteam.name}} are : {{intlteam.World_cups_won}}</h1>
<h1>The total number T20 World Cups won by {{intlteam.name}} are : {{intlteam.T20WC_trophies_won}}</h1>
<h1>The total number Asia Cups won by {{intlteam.name}} are : {{intlteam.Asia_Cups_Won}}</h1>
<h1>The total number Champion Trophies won by {{intlteam.name}} are : {{intlteam.Champion_trophies_won}}</h1>




{% comment %} <h2><a href="{% url 'player:INTLTeamUpdate' pk=intlteam.pk %}">DO YOU WANT TO UPDATE DETAILS?</a></h2>
<h2><a href="{% url 'player:INTLTeamDelete' pk=intlteam.pk %}">DO YOU WANT TO DELETE THE TEAM?</a></h2> {% endcomment %}

{% comment %} <a href="{% url 'player:Playersofintlteam' pk=intlteam.pk %}">View the list of players present in team {{intlteam.name}}</a><br>
<a href="{% url 'player:ODITeamX1' pk=intlteam.pk %}">view the best ODI X1 for team {{intlteam.name}}</a><br>
<a href="{% url 'player:TestTeamX1' pk=intlteam.pk %}">view the best Test X1 for team {{intlteam.name}}</a><br>
<a href="{% url 'player:T20TeamX1' pk=intlteam.pk %}">view the best T20 X1 for team {{intlteam.name}}</a><br> {% endcomment %}
{% endblock %}

<!-- name = models.CharField(max_length=20)
    matches_played = models.IntegerField()
    matches_won = models.IntegerField()
    matches_lost = models.IntegerField()
    trophies_won = models.IntegerField(default=0) -->

templates/player/intlteam_list.html
{%extends 'registration/base.html'%} {% block content %}
<div class="container">
  <div class="jumbotron">
    <div class="iplteamlistheading">
      <h1>HERE IS THE LIST OF INTERNATIONAL TEAMS</h1>
      <h1>THE TOTAL NUMBER OF TEAMS ARE : {{no_of_teams}}</h1>
      <div class="container">
        <div class="row">
          <table>
            <tbody>
              <tr>
                <th>Team Name</th>
                <th>View players</th>
                <th>ODI XI</th>
                <th>T20 XI</th>
                <th>Test XI</th>
                
                {% if user.is_superuser%}
                <th>Edit</th>
                <th>Delete</th>
                {% else %}
                {% endif %}
              </tr>
              {% for intlteam in INTLTeam_list %}
              <tr>
                <td>
                  <a href="{% url 'player:INTLTeamDetail' pk=intlteam.pk %}"
                    >{{ intlteam.name }}</a
                  >
                </td>
                <td>
                  <a href="{% url 'player:Playersofintlteam' pk=intlteam.pk %}"
                    ><button type="button" class="btn btn-info">
                      Players
                    </button></a
                  >
                </td>
                <td>
                  {% if user.is_authenticated %}
                  
                  
                    <a href="{% url 'player:ODITeamX1' pk=intlteam.pk %}"
                      ><button type="button" class="btn btn-info">
                        ODI XI
                      </button></a
                    >
                    {% else %}
                    <a href="{% url 'login' %}"
                      ><button type="button" class="btn btn-info">
                        ODI XI
                      </button></a
                    >
                  {% endif %}
                  </td>
                  <td>
                    {% if user.is_authenticated %}
                    
                    
                      <a href="{% url 'player:T20TeamX1' pk=intlteam.pk %}"
                        ><button type="button" class="btn btn-info">
                          T20 XI
                        </button></a
                      >
                      {% else %}
                      <a href="{% url 'login' %}"
                        ><button type="button" class="btn btn-info">
                          T20 XI
                        </button></a
                      >
                    {% endif %}
                    </td>
                <td>
                  {% if user.is_authenticated %}
                    <a href="{% url 'player:TestTeamX1' pk=intlteam.pk %}"
                      ><button type="button" class="btn btn-info">
                        Test XI
                      </button></a
                    >
                    {% else %}
                    <a href="{% url 'login' %}"
                      ><button type="button" class="btn btn-info">
                        Test XI
                      </button></a
                    >
                  {% endif %}
                  </td>
                {% if user.is_superuser%}
                <td>
                  <a href="{% url 'player:INTLTeamUpdate' pk=intlteam.pk %}"
                    ><button type="button" class="btn btn-warning">
                      Edit
                    </button></a
                  >
                </td>
                <td>
                  <a href="{% url 'player:INTLTeamDelete' pk=intlteam.pk %}"
                    ><button type="button" class="btn btn-danger">
                      Delete
                    </button></a
                  >
                </td>
                {% else %}
                {% endif %}
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}
<!-- {% comment %} <br />
<a href="{% url 'player:ODITeamX1' pk=intlteam.pk %}"
  >view the best ODI X1 for team {{intlteam.name}}</a
><br />
<a href="{% url 'player:TestTeamX1' pk=intlteam.pk %}"
  >view the best Test X1 for team {{intlteam.name}}</a
><br />
<a href="{% url 'player:T20TeamX1' pk=intlteam.pk %}"
  >view the best T20 X1 for team {{intlteam.name}}</a
><br /> {% endcomment %} -->

templates/player/iplteam_detail.html
{%extends 'registration/base.html'%}

{% block content %}
hello, this is the iplteam_detail page 
<h1>The owner of the team is : {{iplteam.owner.username}}</h1>
<h1>The name of the team is : {{iplteam.name}}</h1>
<h1>The total number of matches played by {{iplteam.name}} are : {{iplteam.matches_played}}</h1>
<h1>The total number of matches won by {{iplteam.name}} are : {{iplteam.matches_won}}</h1>
<h1>{{iplteam.name}} has lost {{iplteam.matches_lost}}</h1>
<h1>{{iplteam.name}} has won {{iplteam.trophies_won}} trophies so far!</h1>
<h1>{{iplteam.name}} has a win percentage of {{iplteam.win_p}}</h1>
{% comment %} <h2><a href="{% url 'player:IPLTeamUpdate' pk=iplteam.pk %}">DO YOU WANT TO UPDATE DETAILS?</a></h2>
<h2><a href="{% url 'player:IPLTeamDelete' pk=iplteam.pk %}">DO YOU WANT TO DELETE THE TEAM?</a></h2>
<a href="{% url 'player:Playersofiplteam' pk=iplteam.pk %}">View the list of players present in team {{iplteam.name}}</a>
<a href="{% url 'player:IPLTeamX1' pk=iplteam.pk %}">view the best X1 for team {{iplteam.name}}</a> {% endcomment %}

{% endblock %}

templates/player/iplteam_list.html
{%extends 'registration/base.html'%} {% block content %}
<div class="container">
  <div class="jumbotron">
    <div class="iplteamlistheading">
      <h1>HERE IS THE LIST OF TEAMS</h1>
      <h1>THE TOTAL NUMBER OF TEAMS ARE : {{no_of_teams}}</h1>
    </div>
    {% comment %} {% for iplteam in IPLTeam_list %} {% endcomment %}
    <div class="container">
      <div class="row">
        <table>
          <tbody>
            <tr>
              <th>Team Name</th>
              <th>View Players</th>
              <th>Team XI</th>
              
              {% if user.is_superuser %}
              
              <th>Edit</th>
              <th>Delete</th>
              {% else %}
              {% endif %}
             
            </tr>
            {% for iplteam in IPLTeam_list %}
            <tr>
              <td>
                <a href="{% url 'player:IPLTeamDetail' pk=iplteam.pk %}"
                  >{{iplteam.name}}</a
                >
              </td>
              <td>
                <a href="{% url 'player:Playersofiplteam' pk=iplteam.pk %}"
                  ><button type="button" class="btn btn-info">
                    Players
                  </button></a
                >
              </td>
              <td>
                {% if user.is_authenticated %}
                  <a href="{% url 'player:IPLTeamX1' pk=iplteam.pk %}"
                    ><button type="button" class="btn btn-info">
                      Team XI
                    </button></a
                  >
                  {% else %}
                  <a href="{% url 'login'  %}"
                    ><button type="button" class="btn btn-info">
                      Team XI
                    </button></a
                  >
                {% endif %}
                </td>
              <td>
              {% if user.is_superuser %}
              
                <a href="{% url 'player:IPLTeamUpdate' pk=iplteam.pk %}"
                  ><button type="button" class="btn btn-warning">
                    Edit
                  </button></a
                >
              </td>
              <td>
                <a href="{% url 'player:IPLTeamDelete' pk=iplteam.pk %}"
                  ><button type="button" class="btn btn-danger">
                    Delete
                  </button></a
                >
              {% else %}
              {% endif %}
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
{% endblock %}

<!-- <h2><a href="{% url 'player:IPLTeamUpdate' pk=iplteam.pk %}">DO YOU WANT TO UPDATE DETAILS?</a></h2>
<h2><a href="{% url 'player:IPLTeamDelete' pk=iplteam.pk %}">DO YOU WANT TO DELETE THE TEAM?</a></h2>
<a href="{% url 'player:Playersofiplteam' pk=iplteam.pk %}">View the list of players present in team {{iplteam.name}}</a>
<a href="{% url 'player:IPLTeamX1' pk=iplteam.pk %}">view the best X1 for team {{iplteam.name}}</a> -->

templates/player/player_confirm_delete.html
{%extends 'registration/base.html'%}

{% block content %}
<h1>hello, this is the confirm delete page!</h1>
<form method="POST">
    {% csrf_token %}
    <p>Are you sure you want to delete this team?</p>
    <input type="submit" class="btn btn-danger" value="Confirm">
</form>
{% endblock %}