handcricketReset/urls.py
from operator import index
from player import views
from django.contrib import admin
from django.urls import path
# from numpy import r_
from django.conf.urls import include
from django.urls import include,path
from player import urls
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
router = routers.DefaultRouter()
router.register('iplteams',views.IPLTeamView, basename='iplteams')
router.register('players',views.PlayerView, basename='players')
router.register('intlteams',views.INTLTeamView, basename='intlteams')
router.register('users',views.UserView, basename='users')
router.register('profileextends',views.ProfileExtendView, basename='profileextends')
# router.register('users',views.User, basename='users')
# router.register('profileextends',views.ProfileExtendView, basename='profileextends')
# routeriplteams = routers.DefaultRouter()
# routeriplteams.register('iplteams',views.IPLTeamView, basename='iplteams')
# routerintlteams = routers.DefaultRouter()
# routerintlteams.register('intlteams',views.INTLTeamView, basename='intlteams')
# routerusers = routers.DefaultRouter()
# routerusers.register('users',views.UserView, basename='users')
# routerprofileextend = routers.DefaultRouter()
# routerprofileextend.register('profileextends',views.UserView, basename='profileextends')
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('player.urls',namespace='player')),
    path('login/',auth_views.LoginView.as_view(template_name="registration/login.html"),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('signup/',views.SignUp.as_view(),name='signup'),
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path('api/',include(router.urls)),
]
if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

player/urls.py
from operator import index
from django.shortcuts import render
from player import views
from django.contrib import admin
from django.urls import path
# from numpy import place, r_
from django.conf.urls import include
from django.contrib.auth import views as auth_views
from player import views
app_name = 'player'

urlpatterns = [
    path('',views.AboutView,name='about'),
    path('IPLTeamList/',views.IPLTeamListView.as_view(),name='IPLTeamList'),
    path('newiplteam/',views.CreateIPLTeam.as_view(),name='newiplteam'),
    path('IPLTeamDetail/<int:pk>/',views.IPLTeamDetailView.as_view(),name='IPLTeamDetail'),
    path('IPLTeamUpdate/<int:pk>/',views.IPLTeamUpdateView.as_view(),name='IPLTeamUpdate'),
    path('IPLTeamDelete/<int:pk>/',views.IPLTeamDeleteView.as_view(),name='IPLTeamDelete'),
    path('newintlteam/',views.CreateINTLTeam.as_view(),name='newintlteam'),
    path('INTLTeamList/',views.INTLTeamListView.as_view(),name='INTLTeamList'),
    path('INTLTeamDetail/<int:pk>',views.INTLTeamDetailView.as_view(),name='INTLTeamDetail'),
    path('INTLTeamUpdate/<int:pk>/',views.INTLTeamUpdateView.as_view(),name='INTLTeamUpdate'),
    path('INTLTeamDelete/<int:pk>/',views.INTLTeamDeleteView.as_view(),name='INTLTeamDelete'),
    path('newplayer/',views.CreatePLayer.as_view(),name='newplayer'),
    path('PlayerList/',views.PlayerList.as_view(),name='PlayerList'),
    path('PlayerDetail/<int:pk>/',views.PlayerDetailView.as_view(),name='PlayerDetail'),
    path('PlayerUpdate/<int:pk>/',views.PLayerUpdateView.as_view(),name='PlayerUpdate'),
    path('PlayerDelete/<int:pk>/',views.PLayerDeleteView.as_view(),name='PlayerDelete'),
    path('MyProfile/',views.my_profile,name='MyProfile'),
    path('Playersofintlteam/<int:pk>',views.get_players_of_intl_team,name='Playersofintlteam'),
    path('Playersofipllteam/<int:pk>',views.get_players_of_ipl_team,name='Playersofiplteam'),
    path('ODITeamX1/<int:pk>/',views.ODITeamX1,name='ODITeamX1'),
    path('TestTeamX1/<int:pk>/',views.TestTeamX1,name='TestTeamX1'),
    path('T20TeamX1/<int:pk>/',views.T20TeamX1,name='T20TeamX1'),
    path('IPLTeamX1/<int:pk>/',views.IPLTeamX1,name='IPLTeamX1'),
    path('GiftPlayer/<int:pk>/',views.gift_player,name="GiftPlayer"),
    path('MyT20TeamX1/',views.MyT20TeamX1,name='MyT20TeamX1'),
    path('MYIPLTeamX1/',views.MYIPLTeamX1,name='MYIPLTeamX1'),
    path('MyTestTeamX1/',views.MyTestTeamX1,name='MyTestTeamX1'),
    path('MyODITeamX1/',views.MyODITeamX1,name='MyODITeamX1'),
    path('worldODIXI/',views.worldODIXI,name='worldODIXI'),
    path('worldTestXI/',views.worldTestXI,name='worldTestXI'),
    path('worldT20XI/',views.worldT20XI,name='worldT20XI'),
    path('IPLXI/',views.IPLXI,name='IPLXI'),
    path('ExtraProfile/',views.ExtraProfile.as_view(),name='ExtraProfile'),
    path('ProfileUpdateView/',views.ProfileUpdateView.as_view(),name='ProfileUpdateView'),
    path('ViewStats/',views.ViewStats,name='ViewStats'),
    path('ViewMyStats/',views.viewuserStats,name='ViewMyStats'),
    path('search_venues/',views.search_venues,name='search_venues'),
]

templates/bestXIs/TeamX1.html
{% extends 'registration/base.html' %}
{%block content%}

{% if result1 == True or result2 == True or result3 == True or result4 == True or result5 == True or result6 == True or result7 == True or res1 == True or res2 == True or res3 == True or res4 == True or res5 %}


<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter">
    Oops, it didn't work! View the problem
  </button>
  
  <!-- Modal -->
  <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLongTitle">Insufficient Players</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          
          {% if result1 == True %}
          <a href="{%url 'player:newplayer'%}">Please insert openers!</a>
          {% elif result2 == True %}
          <a href="{%url 'player:newplayer'%}">Please insert a middle order batsman!</a> 
          {% elif result3 == True %}
          <a href="{%url 'player:newplayer'%}">Please Insert a Finisher</a>
          {% elif result4 == True %}
          <a href="{%url 'player:newplayer'%}">Please insert a batting allrounder!</a>
          {% elif result5 == True %}
          <a href="{%url 'player:newplayer'%}">Please insert a bowling allrounder!</a>
          {% elif result6 == True %}
          <a href="{%url 'player:newplayer'%}">Please insert a fast bowler!</a>
          {% elif result7 == True %}
          <a href="{%url 'player:newplayer'%}">Please insert a spin bowler!</a>
          {% elif res1 == True %}
          <a href="{%url 'player:newplayer'%}">There is a repetition of opener and batting allrounder -> please insert an opener or a batting allrounder and try again!</a>
          {% elif res2 == True %}
          <a href="{%url 'player:newplayer'%}">There is a repetition of middle order batsman and batting allrounder -> please insert an middle order batsman or a batting allrounder and try again!</a>
          {% elif res3 == True %}
          <a href="{%url 'player:newplayer'%}">There is a repetition of fast bowler and bowling allrounder -> please insert an fast bowler or a bowling allrounder and try again!</a>
          {% elif res4 == True %}
          <a href="{%url 'player:newplayer'%}">There is a repetition of spin bowler and bowling allrounder -> please insert an spin bowler or a bowling allrounder and try again!</a>
          {% elif res5 == True %}
          <a href="{%url 'player:newplayer'%}">There is a repetition of finisher and batting allrounder -> please insert an finisher or a batting allrounder and try again!</a>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary">Save changes</button>
        </div>
      </div>
    </div>
  </div>
{% else %}
{% endif %}

{% else %}
{{heading}}
<div class="container">
    <div class="row">
      <div class="col mx-1">
          <table class="table table-striped table">
            <thead class="thead-dark">
              <tr>
                  <th>Name</th>
                  <th>Country</th>
                  <th>IPL</th>
              </tr>
            </thead>
              <tbody>
                  {% for x in openers %}
                  <tr>
                      <td>
                          
                          <a class="player_urls_list" href="{% url 'player:PlayerDetail' pk=x.pk %}">{{x.name}}</a>
                      </td>
                      <td>
                          
                      </td>
                      <td>
                          
                      </td>
                  </tr>
                  {% endfor %} {% for x in Middle_Order %}
                  <tr>
                      <td>
                          <a class="player_urls_list" href="{% url 'player:PlayerDetail' pk=x.pk %}">{{x.name}}</a>
                      </td>
                      <td>
                          
                      </td>
                      <td>
                          
                      </td>
                  </tr>
                  {% endfor %} {% for x in Finisher %}
                  <tr>
                      <td>
                          <a class="player_urls_list" href="{% url 'player:PlayerDetail' pk=x.pk %}">{{x.name}}</a>
                      </td>
                      <td>
                          
                      </td>
                      <td>
                          
                      </td>
                      {% endfor %}
                  </tr>
                  <tr>
                      <td>
                          <a class="player_urls_list" href="{% url 'player:PlayerDetail' pk=Batting_Allrounder.pk %}">{{Batting_Allrounder.name}}</a>
                      </td>
                      <td>
                          <img src="{{Batting_Allrounder.intlteam.flagintl.url}}" alt="">
                      </td>
                      <td>
                          <img src="{{Batting_Allrounder.iplteam.flagipl.url}}" alt="IPL NOT PLAYED">
                      </td>
                  </tr>
                  <tr>
                      <td>
                          <a class="player_urls_list" href="{% url 'player:PlayerDetail' pk=Bowling_Allrounder.pk %}">{{Bowling_Allrounder.name}}</a>
                      </td>
                      <td>
                          
                      </td>
                      <td>
                          
                      </td>
                  </tr>
                  {% for x in Fast_Bowler %}
                  <tr>
                      <td>
                          <a class="player_urls_list" href="{% url 'player:PlayerDetail' pk=x.pk %}">{{x.name}}</a>
                      </td>
                      <td>
                          
                      </td>
                      <td>
                          
                      </td>
                  </tr>
                  {% endfor %}
                  {% for x in Spin_Bowler %}
                  <tr>
                      <td>
                          <a class="player_urls_list" href="{% url 'player:PlayerDetail' pk=x.pk %}">{{x.name}}</a>
                      </td>
                      <td>
                          
                      </td>
                      <td>
                          
                      </td>
                  </tr>
                  {% endfor %}
              </tbody>
          </table>
      </div>
    </div>
  </div>

{% endif %}





{%endblock%}

templates/bestXIs/worldXI.html
{%extends 'registration/base.html'%} {% block content %}
<div class="container">
  <div class="row">
    <div class="col mx-1">
      <table class="table table-striped table">
        <thead class="thead-dark">
          <tr>
            <th>Name</th>
            <th>Country</th>
            <th>IPL</th>
          </tr>
        </thead>
        <tbody>
          {% for x in openers %}
          <tr>
            <td>
              <a
                class="player_urls_list"
                href="{% url 'player:PlayerDetail' pk=x.pk %}"
                >{{x.name}}</a
              >
            </td>
            <td>
              <img src="{{x.intlteam.flagintl.url}}" alt="NOT PLAYED" />
            </td>
            <td>
              <img src="{{x.iplteam.flagipl.url}}" alt="NOT PLAYED" />
            </td>
          </tr>
          {% endfor %} {% for x in middle_order %}
          <tr>
            <td>
              <a
                class="player_urls_list"
                href="{% url 'player:PlayerDetail' pk=x.pk %}"
                >{{x.name}}</a
              >
            </td>
            <td>
              <img src="{{x.intlteam.flagintl.url}}" alt="NOT PLAYED" />
            </td>
            <td>
              <img src="{{x.iplteam.flagipl.url}}" alt="NOT PLAYED" />
            </td>
          </tr>
          {% endfor %} {% for x in finisher %}
          <tr>
            <td>
              <a
                class="player_urls_list"
                href="{% url 'player:PlayerDetail' pk=x.pk %}"
                >{{x.name}}</a
              >
            </td>
            <td>
              <img src="{{x.intlteam.flagintl.url}}" alt="NOT PLAYED" />
            </td>
            <td>
              <img src="{{x.iplteam.flagipl.url}}" alt="NOT PLAYED" />
            </td>
          </tr>
          {% endfor %}
          <tr>
            <td>
              <a
                class="player_urls_list"
                href="{% url 'player:PlayerDetail' pk=batting_allrounder.pk %}"
                >{{batting_allrounder.name}}</a
              >
            </td>
            <td>
              <img
                src="{{batting_allrounder.intlteam.flagintl.url}}"
                alt="NOT PLAYED"
              />
            </td>
            <td>
              <img
                src="{{batting_allrounder.iplteam.flagipl.url}}"
                alt="NOT PLAYED"
              />
            </td>
          </tr>
          <tr>
            <td>
              <a
                class="player_urls_list"
                href="{% url 'player:PlayerDetail' pk=bowling_allrounder.pk %}"
                >{{bowling_allrounder.name}}</a
              >
            </td>
            <td>
              <img
                src="{{bowling_allrounder.intlteam.flagintl.url}}"
                alt="NOT PLAYED"
              />
            </td>
            <td>
              <img
                src="{{bowling_allrounder.iplteam.flagipl.url}}"
                alt="NOT PLAYED"
              />
            </td>
          </tr>
          {% for x in bowlers %}
          <tr>
            <td>
              <a
                class="player_urls_list"
                href="{% url 'player:PlayerDetail' pk=x.pk %}"
                >{{x.name}}</a
              >
            </td>
            <td>
              <img src="{{x.intlteam.flagintl.url}}" alt="NOT PLAYED" />
            </td>
            <td>
              <img src="{{x.iplteam.flagipl.url}}" alt="NOT PLAYED" />
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>
{% endblock %}